/**************************************************************************/
/*  gdclass_macros.hpp                                                    */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

#ifndef GDCLASS_MACROS_HPP
#define GDCLASS_MACROS_HPP

#ifdef _MSC_VER
#define GDCLASS_PRAGMA(x) __pragma(x)

// C4100: unreferenced formal parameter
#define GDCLASS_DISABLE_WARNINGS  \
	GDCLASS_PRAGMA(warning(push)) \
	GDCLASS_PRAGMA(warning(disable : 4100 4800))

#define GDCLASS_RESTORE_WARNINGS GDCLASS_PRAGMA(warning(pop))
#endif // _MSC_VER

#ifdef __GNUC__
#define GDCLASS_PRAGMA(x) _Pragma(#x)

#define GDCLASS_DISABLE_WARNINGS        \
	GDCLASS_PRAGMA(GCC diagnostic push) \
	GDCLASS_PRAGMA(GCC diagnostic ignored "-Wunused-parameter")

#define GDCLASS_RESTORE_WARNINGS GDCLASS_PRAGMA(GCC diagnostic pop)
#endif // __GNUC__

// NOLINTBEGIN: This suppression propagates to any code generated by `GDCLASS` as well
#define GDCLASS_QUIET(m_class, m_inherits) \
	GDCLASS_DISABLE_WARNINGS               \
	GDCLASS(m_class, m_inherits)           \
	GDCLASS_RESTORE_WARNINGS
// NOLINTEND

#endif // GDCLASS_MACROS_HPP
